config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :parts
  resources :actors
  resources :films do
    collection do
      get :search
    end
  end 

  resources :cinemas
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :film
  belongs_to :actor

  validates :role, :film_id, :actor_id, presence: true

  accepts_nested_attributes_for :actor, allow_destroy: true
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Создано успешно!' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Обновленно успешно!' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Удалено успешно!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:role, :film_id, :actor_id)
    end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.haml
= form_for @part do |f|
  = error_messages_for @part

  .field
    = f.label :role
    = f.text_area :role
  .field
    = f.label :film
    = f.text_field :film
  .field
    = f.label :actor
    = f.text_field :actor
  .actions
    = f.submit 'Сохранить'

app/views/parts/edit.html.haml
%h1 Редактирование таблицы

= render 'form'

= link_to 'Показать', @part
\|
= link_to 'Назад', parts_path

app/views/parts/index.html.haml
%h1 Список

%table
  %thead
    %tr
      %th Роль
      %th Фильм
      %th Актёр
      %th
      %th
      %th

  %tbody
    - @parts.each do |part|
      %tr
        %td= part.role
        %td= part.film
        %td= part.actor
        %td= link_to 'Показать', part
        %td= link_to 'Редактировать', edit_part_path(part)
        %td= link_to 'Удалить', part, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'Новая запись', new_part_path

app/views/parts/new.html.haml
%h1 Новая запись

= render 'form'

= link_to 'Назад', parts_path

app/views/parts/show.html.haml
%p#notice= notice

%p
  %b Роль:
  = @part.role
%p
  %b Фильм:
  = @part.film
%p
  %b Актёр:
  = @part.actor

= link_to 'Редактировать', edit_part_path(@part)
\|
= link_to 'Назад', parts_path