config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :parts
  resources :actors
  resources :films do
    collection do
      get :search
    end
  end 

  resources :cinemas
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/film.rb
class Film < ActiveRecord::Base
  has_many :parts
  has_many :addresses

  accepts_nested_attributes_for :parts, allow_destroy: true

  validates :name, presence: true
  validates :genre, presence: true
  validates :lasting, presence: true
  validates :country, presence: true
  validates :companies, presence: true
  validates :min_age, presence: true
  def destroy_addresses_parts
    self.addresses.each{|x| x.destroy}
    self.parts.each{|x| x.destroy}
  end

  def self.search(params)
    result = Film.eager_load(:parts, parts: :actor)

    if params['min_age'].present?
      result = result.where(min_age: params['min_age'])
    end
    if params['companies'].present?
      result = result.where(companies: params['companies'])
    end
    if params['country'].present?
      result = result.where(country: params['country'])
    end
    if params['lasting'].present?
      result = result.where(lasting: params['lasting'])
    end
    if params['genre'].present?
      result = result.where(genre: params['genre'])
    end
    if params['name'].present?
      result = result.where(name: params['name'])
    end

    if params['role'].present?
      result = result.where("parts.role": params['role'])
    end

    if params['fn'].present?
      result = result.where("actors.fn": params['fn'])
    end
    if params['ln'].present?
      result = result.where("actors.ln": params['ln'])
    end
    if params['sn'].present?
      result = result.where("actors.sn": params['sn'])
    end
    if params['birthday'].present?
      result = result.where("actors.birthday": params['birthday'])
    end
    result.all
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]
  def search
    if params.has_key?('search')
      @films = Film.search(params['search'])
    else
      @films = []
    end
    params['search'] ||= {}
  end



  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Создано успешно!' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Обновленно успешно!' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Удалено успешно!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:name, :genre, :lasting, :country, :companies, :min_age,
 {parts_attributes: [:_destroy, :id, :role, :actor_id, :film_id,
          actor_attributes: [:_destroy, :id, :ln, :fn, :sn, :birthday]]})
    end
end

app/helpers/films_helper.rb
module FilmsHelper
  def new_actor_form(form)
    new_object = Actor.new
    form.fields_for(:actor, new_object) do |ar|
      render('films/one_actor_form', ar: ar)
    end
  end

  def link_to_add_part(form)
    # Создаём новый объект. Аналог build в ранних примерах
    new_object = Part.new
    # Нам нужна nested-форма. В момент создания ссылки её ещё нет. Создадим её
    # Все role_users в форме имеют свой номер
    # Мы его пока заменям на фразу new_ru
    fields = form.fields_for(:parts, new_object,
      :child_index => 'new_part') do |fr|
      render('films/one_part_form', fr: fr, i: 'Новая')
    end
    # Ссылка будет обрабатываться javascript-ом поэтому адрес фиктивный
    link_to(?#, class: 'btn btn-info',
        id: 'add_part_link', data: {content: "#{fields}"}) do
      fa_icon("plus") + " Новая роль"
    end
  end

  def link_to_remove_part(form)
    # При удалении nested-конструкции. Она реально не удаляется
    # Соответствующий html-блок скрывается
    # При этом выставляется значение специального поля _destroy
    # По этому поля rails понимает, что связь надо удалить
    form.hidden_field(:_destroy, class: 'remove_fields') +
        # Ссылка будет обрабатываться javascript-ом поэтому адрес фиктивный
        link_to(?#, class: 'remove_fields remove_part') do
      fa_icon('times', title: 'Удалить роль') + ' Удалить'
    end
  end
end

app/views/films/_form.html.haml
= form_for @film do |f|
  = error_messages_for @film
  .form-actions.bottom20
    = f.submit nil, class: 'btn btn-primary'
  .row
    .col-md-6
      .form-group
        = f.label :name
        = f.text_area :name, class: 'form-control', rows: 1
        = f.error_messages_for(:name)
    .col-md-6
      .form-group
        = f.label :genre
        = f.text_area :genre, class: 'form-control', rows: 1
        = f.error_messages_for(:genre)
  .row
    .col-md-6
      .form-group
        = f.label :lasting
        = f.text_area :lasting, class: 'form-control', rows: 1
        = f.error_messages_for(:lasting)
    .col-md-6
      .form-group
        = f.label :country
        = f.text_area :country, class: 'form-control', rows: 1
        = f.error_messages_for(:country)
  .row
    .col-md-6
      .form-group
        = f.label :companies
        = f.text_area :companies, class: 'form-control', rows: 1
        = f.error_messages_for(:companies)
    .col-md-6
      .form-group
        = f.label :min_age
        = f.number_field :min_age, class: 'form-control'
        = f.error_messages_for(:min_age)

  .row.bottom20
    .col-md-12
      = link_to_add_part(f)
  - i = 0
  = f.fields_for(:parts) do |fr|
    = fr.hidden_field(:id)
    = render('films/one_part_form', fr: fr, i: i += 1)

app/views/films/_one_actor_form.html.haml
= ar.hidden_field(:id)
.col-md-12
  .form-group
    = ar.label :ln
    = ar.text_field :ln, class: 'form-control'
    = ar.error_messages_for(:ln)
.col-md-12
  .form-group
    = ar.label :fn
    = ar.text_field :fn, class: 'form-control'
    = ar.error_messages_for(:fn)
.col-md-12
  .form-group
    = ar.label :sn
    = ar.text_field :sn, class: 'form-control'
    = ar.error_messages_for(:sn)
.col-md-12
  .form-group
    = ar.label :birthday
    .input-group.date.datepicker
      = ar.text_field :birthday, value: lnil(ar.object.birthday), class: 'form-control'
      %span.input-group-addon
        %span.glyphicon.glyphicon-calendar
    = ar.error_messages_for(:birthday)
-# .col-md-12
-#   .form-group
-#     = ar.check_box :_destroy
-#     = ar.label :_destroy, "Удалить?"

app/views/films/_one_part_form.html.haml
.col-md-6
  %div{class: 'panel panel-'+ (i.kind_of?(Integer) ? 'success' : 'info')}
    .panel-heading
      Роль
      = i
      %span.toright
        = link_to_remove_part(fr)

      .clearfix
    .panel-body
      .row
        .col-md-6
          .form-group
            = fr.label :role
            = fr.text_field :role, class: 'form-control'
            = fr.error_messages_for(:role)
        .col-md-6
          .form-group
            = fr.label :actor_id
            -# actor_options() в actors_helper
            -# При выборе текущего актёра, его можно изменять, при выборе нового,
            -# поля для него скрываются, при выборе пустоты в актёрах -
            -# можно создать новый.
            = fr.select :actor_id, actor_options(fr.object.actor_id),
            {include_blank: true}, class: 'form-control actor-select', "data-current-id": fr.object.actor_id
            = fr.error_messages_for(:actor_id)

      .row
        %fieldset.center
          %legend Поля для человека
          -# new_actor_form(fr) и exist_actor_form(fr) в actors_helper
          .left.actor-main-fields{"data-content-new": "#{new_actor_form(fr)}",
          "data-content-exist": "#{exist_actor_form(fr)}"}
            = fr.fields_for(:actor) do |ar|
              = render 'films/one_actor_form', ar: ar

app/views/films/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.films.edit')
  %li
    = link_to(@film.name, @film)
  %li
    = link_to 'Фильмы', films_path
  %li
    Кинотеатры/Фильмы

.page-header
  %h1= t('headers.films.edit')

= render 'form'

app/views/films/index.html.haml
=breadcrumb_tag do
  %li.active
    Фильмы
  %li
    Кинотеатры/Фильмы

.page-header
  %h1= t('headers.films.index')

= link_to new_film_path, class: 'btn btn-success' do
  = fa_icon :plus
  = t('buttons.new.film')
= link_to search_films_path, class: 'btn btn-warning' do
  = fa_icon :search
  = t('buttons.films.Поиск')

.row
  .col-xs-12
    %table.table.table-hover
      %tbody
        - @films.each do |film|
          %tr.active
            %th= Film.human_attribute_name(:name)
            %td= film.name
          %tr
            %th= Film.human_attribute_name(:genre)
            %td= film.genre
          %tr
            %th= Film.human_attribute_name(:lasting)
            %td= film.lasting
          %tr
            %th= Film.human_attribute_name(:country)
            %td= film.country
          %tr
            %th= Film.human_attribute_name(:companies)
            %td= film.companies
          %tr
            %th= Film.human_attribute_name(:min_age)
            %td= film.min_age
          %tr
            %td
              = link_to film, class: 'btn btn-warning' do
                = fa_icon :eye
                = t('buttons.show')
              = link_to edit_film_path(film), class: 'btn btn-info' do
                = fa_icon :edit
                = t('buttons.edit')
              = link_to film, :method => :delete,
              :data => { :confirm => t('buttons.confirm.film') },
              class: 'btn btn-danger' do
                = fa_icon :times
                = t('buttons.destroy')
            %td

app/views/films/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.films.new')
  %li
    = link_to 'Фильмы', films_path
  %li
    Кинотеатры/Фильмы

.page-header
  %h1= t('headers.films.new')

= render 'form'

app/views/films/search.html.haml
=breadcrumb_tag do
  %li.active
    = t('app.films.Поиск')
  %li
    = link_to 'Фильмы', films_path


.page-header

  %h1= t('headers.films.Поиск')

= form_tag(search_films_path(), :method => "get") do
  .row
  = link_to films_path, class: 'btn btn-warning' do
    = t('buttons.Вернуться на страницу фильмов')
  .row
    .col-md-12
      %h2 Поля для фильма
  .row
    .col-md-6
      .form-group
        = label_tag 'search[name]', "Название:"
        = text_field_tag 'search[name]', nil,
        placeholder: "Введите название фильма", class: 'form-control'
    .col-md-6
      .form-group
        = label_tag 'search[genre]', "Жанр:"
        = text_field_tag 'search[genre]', nil,
        placeholder: "Введите жанр", class: 'form-control'
  .row
    .col-md-6
      .form-group
        = label_tag 'search[lasting]', "Продолжительность:"
        = text_field_tag 'search[lasting]', nil,
        placeholder: "Введите продолжительность", class: 'form-control'
    .col-md-6
      .form-group
        = label_tag 'search[companies]', "Страна происхождения"
        = text_field_tag 'search[companies]', nil,
        placeholder: "Введите стану происхождения", class: 'form-control'
    .col-md-12
      .form-group
        = label_tag 'search[min_age]', "Возраст:"
        = text_field_tag 'search[min_age]', nil,
        placeholder: "Введите минимальный возраст разрешенный для просмотра", class: 'form-control'

  .row
    .col-md-12
      %h2 Поля для роли
    .col-md-6
      .form-group
        = label_tag 'search[role]', "Роль:"
        = text_field_tag 'search[role]', nil,
        placeholder: "Введите роль", class: 'form-control'
  .row
    .col-md-12
      %h2 Поля для актёра
    .col-md-6
      .form-group
        = label_tag 'search[fn]', "Имя:"
        = text_field_tag 'search[fn]', nil,
        placeholder: "Введите имя", class: 'form-control'

  .row
    .col-md-6
      .form-group
        = label_tag 'search[ln]', "Фамилия:"
        = text_field_tag 'search[ln]', nil,
        placeholder: "Введите фамилию", class: 'form-control'
  .row
    .col-md-6
      .form-group
        = label_tag 'search[sn]', "Отчество:"
        = text_field_tag 'search[sn]', nil,
        placeholder: "Введите отчество", class: 'form-control'
  .row
    .col-md-6
      .form-group
        = label_tag 'search[birthday]', "Дата рождения:"
        = text_field_tag 'search[birthday]', nil,
        placeholder: "Введите дату рождения", class: 'form-control'


  .row
    .col-md-12.left
      = submit_tag(:search_button, value: 'Поиск', class: 'btn btn-default')
      = link_to search_films_path, class: 'btn btn-warning' do
        = t('buttons.Очистить')
      = link_to root_path, class: "btn btn-primary" do
        = t('buttons.Вернуться на главную страницу')

  %h3= t('headers.film.Результат поиска')
  %dl.dl-horizontal
  - @films.each do |film|
    .row
      = film.name.to_s + " / "
      = film.genre.to_s + " / "
      = film.lasting.to_s + " / "
      = film.country.to_s + " / "
      = film.companies.to_s + " / "
      = film.min_age.to_s + " / "

      = link_to film, class: 'btn btn-info' do
        = fa_icon "eye"
        = t('buttons.show')

app/views/films/show.html.haml
=breadcrumb_tag do
  %li.active
    = @film.name
  %li
    = link_to 'Фильмы', films_path
  %li
    Кинотеатры/Фильмы

%h1= @film.name

%dl
  %dt= Film.human_attribute_name(:name)
  %dd= @film.name

  %dt= Film.human_attribute_name(:genre)
  %dd= @film.genre

  %dt= Film.human_attribute_name(:lasting)
  %dd= @film.lasting

  %dt= Film.human_attribute_name(:country)
  %dd= @film.country

  %dt= Film.human_attribute_name(:companies)
  %dd= @film.companies

  %dt= Film.human_attribute_name(:min_age)
  %dd= @film.min_age

= link_to edit_film_path(@film), class: 'btn btn-info' do
  = fa_icon :edit
  = t('buttons.edit')
= link_to @film, :method => :delete,
:data => { :confirm => t('buttons.confirm.film') },
class: 'btn btn-danger' do
  = fa_icon :times
  = t('buttons.destroy')